AWSTemplateFormatVersion: 2010-09-09
Description: IAM policy for Sedai Integration

Parameters:
  SedaiIntegrationServiceRole:
    Type: String
    Description: The name of the Role
  PolicyIncludeLocation:
    Type: String
    Description: S3 URL of the policy statement
  Service:
    Type: String
    Description: The name of the service
  Permission:
    Type: String
    Description: Read or Write permission

Resources:
  SedaiIntegrationServicePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub sedai-integration-service-${Service}-${Permission}
      PolicyDocument:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: !Ref PolicyIncludeLocation
      Roles:
        - Ref: SedaiIntegrationServiceRole

  SedaiIntegrationCURS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName:
        Fn::Sub: "sedai-cur-bucket-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: BucketOwnerFullControl
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Object&Version Expiration
            Status: Enabled
            NoncurrentVersionExpirationInDays: 32 # 1 month

  SedaiIntegrationCURS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Bucket:
        Ref: SedaiIntegrationCURS3Bucket
      PolicyDocument:
        Id: SedaiIntegrationCURS3BucketPolicy
        Version: "2012-10-17"
        Statement:
          - Sid: AllowReadBilling
            Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketPolicy
            Resource:
              - Fn::Sub: "arn:${AWS::Partition}:s3:::${SedaiIntegrationCURS3Bucket}"
              - Fn::Sub: "arn:${AWS::Partition}:s3:::${SedaiIntegrationCURS3Bucket}/*"
            Condition:
              StringEquals:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:cur:${AWS::Region}:${AWS::AccountId}:definition/*"
                aws:SourceAccount: !Ref AWS::AccountId
          - Sid: AllowWriteBilling
            Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action:
              - s3:PutObject
            Resource:
              - Fn::Sub: "arn:${AWS::Partition}:s3:::${SedaiIntegrationCURS3Bucket}/*"
            Condition:
              StringEquals:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:cur:${AWS::Region}:${AWS::AccountId}:definition/*"
                aws:SourceAccount: !Ref AWS::AccountId

  SedaiIntegrationCURReportDefinition:
    Type: AWS::CUR::ReportDefinition
    DependsOn:
      - SedaiIntegrationCURS3Bucket
      - SedaiIntegrationCURS3BucketPolicy
    Properties:
      AdditionalSchemaElements:
        - RESOURCES
      Compression: GZIP
      Format: textORcsv
      RefreshClosedReports: True
      ReportName: sedai-cur-reports
      ReportVersioning: OVERWRITE_REPORT
      S3Bucket: !Ref SedaiIntegrationCURS3Bucket
      S3Prefix: !Sub "cur/${AWS::AccountId}"
      S3Region: !Ref AWS::Region
      TimeUnit: HOURLY

Outputs:
  SedaiIntegrationCURS3Bucket:
    Description: CUR Bucket
    Value: !Ref SedaiIntegrationCURS3Bucket
    Export: 
      Name: SedaiIntegrationCURS3Bucket
