AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template to provide permission for Sedai
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sedai app configuration section"
        Parameters:
          - UniqueExternalId
      - Label:
          default: "Permission section"
        Parameters:
          - ReadOnly
          - LambdaRequired
          - ECSRequired
          - KubernetesRequired
          - EC2InstanceRequired
          - S3StorageRequired
          - EBSStorageRequired
          - RDSRequired
    ParameterLabels:
      UniqueExternalId:
        default: "Enter the unique external ID"
      ReadOnly:
        default: "Do you want Sedai to only have read-only access to your account?"
      LambdaRequired:
        default: "Would you like to give Sedai the permissions to work with your Lambda workloads?"
      ECSRequired:
        default: "Would you like to give Sedai the permissions to work with your ECS workloads?"
      KubernetesRequired:
        default: "Would you like to give Sedai the permissions to work with your EKS workloads?"
      EC2InstanceRequired:
        default: "Would you like to give Sedai the permissions to work with your EC2 Instance workloads?"
      S3StorageRequired:
        default: "Would you like to give Sedai the permissions to work with your S3 Storage workloads?"
      EBSStorageRequired:
        default: "Would you like to give Sedai the permissions to work with your EBS Storage workloads?"
      RDSRequired:
        default: "Would you like to give Sedai the permissions to work with your RDS workloads?"

Parameters:
  UniqueExternalId:
    Type: String
    Description: "Keep this empty (recommended) to generate a unique external ID in the ext-{AWSAccountID} format."
  ReadOnly:
    Description: "Select Yes to give read-only access. Select No if you want to give Sedai the permission to start optimizing the workloads"
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  LambdaRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"
  ECSRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"
  KubernetesRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"      
  EC2InstanceRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"      
  S3StorageRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"
  EBSStorageRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"
  RDSRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"

Mappings:
  PolicyReadOnlyMap:
    Common:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-common-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-common-rw.json"
    Lambda:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-lambda-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-lambda-rw.json"
    ECS:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-ecs-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-ecs-rw.json"
    Kubernetes:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-kubernetes-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-kubernetes-rw.json"      
    EC2Instance:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-ec2instance-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-ec2instance-rw.json"
    S3Storage:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-storages3-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-storages3-rw.json"
    EBSStorage:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-storageebs-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-storageebs-rw.json"
    RDS:
      "Yes": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-rds-r.json"
      "No": "s3://sedai-onboarding-templates-prod/nested/sedai-integration-include-rds-rw.json"
Conditions:
  UniqueExternalIdPresent: !Not
    - !Equals
      - !Ref UniqueExternalId
      - ""
  IsReadOnly: !Equals
    - !Ref ReadOnly
    - "Yes"
  IsLambdaRequired: !Equals
    - !Ref LambdaRequired
    - "Yes"
  IsECSRequired: !Equals
    - !Ref ECSRequired
    - "Yes"
  IsKubernetesRequired: !Equals
    - !Ref KubernetesRequired
    - "Yes"    
  IsEC2InstanceRequired: !Equals
    - !Ref EC2InstanceRequired
    - "Yes"
  IsS3StorageRequired: !Equals
    - !Ref S3StorageRequired
    - "Yes"
  IsEBSStorageRequired: !Equals
    - !Ref EBSStorageRequired
    - "Yes"
  IsRDSRequired: !Equals
    - !Ref RDSRequired
    - "Yes"
Resources:
  SedaiIntegrationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sedai-integration-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 504216784688
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals: !If
                - UniqueExternalIdPresent
                - sts:ExternalId: !Ref UniqueExternalId
                - sts:ExternalId: !Sub ext-${AWS::AccountId}
      Path: "/"

  SedaiIntegrationCommonPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, Common, !Ref ReadOnly]
        Service: common
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-inlinepolicy.yml"

  SedaiIntegrationLambdaPolicy:
    Type: AWS::CloudFormation::Stack
    Condition: IsLambdaRequired
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, Lambda, !Ref ReadOnly]
        Service: lambda
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-managedpolicy.yml"

  SedaiIntegrationECSPolicy:
    Type: AWS::CloudFormation::Stack
    Condition: IsECSRequired
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, ECS, !Ref ReadOnly]
        Service: ecs
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-managedpolicy.yml"

  SedaiIntegrationKubernetesPolicy:
    Type: AWS::CloudFormation::Stack
    Condition: IsKubernetesRequired
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, Kubernetes, !Ref ReadOnly]
        Service: kubernetes
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-managedpolicy.yml"
  
  SedaiIntegrationEC2InstancePolicy:
    Type: AWS::CloudFormation::Stack
    Condition: IsEC2InstanceRequired
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, EC2Instance, !Ref ReadOnly]
        Service: ec2instance
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-managedpolicy.yml"
  

  
  SedaiIntegrationS3StoragePolicy:
    Type: AWS::CloudFormation::Stack
    Condition: IsS3StorageRequired
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, S3Storage, !Ref ReadOnly]
        Service: s3storage
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-inlinepolicy.yml"

  SedaiIntegrationEBSStoragePolicy:
    Type: AWS::CloudFormation::Stack
    Condition: IsEBSStorageRequired
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, EBSStorage, !Ref ReadOnly]
        Service: ebsstorage
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-inlinepolicy.yml"
  SedaiIntegrationRDSPolicy:
    Type: AWS::CloudFormation::Stack
    Condition: IsRDSRequired
    Properties:
      Parameters:
        SedaiIntegrationServiceRole: !Ref SedaiIntegrationServiceRole
        PolicyIncludeLocation:
          !FindInMap [PolicyReadOnlyMap, RDS, !Ref ReadOnly]
        Service: rds
        Permission: !If [IsReadOnly, read, write]
      TemplateURL: "https://sedai-onboarding-templates-prod.s3.amazonaws.com/nested/sedai-integration-nested-managedpolicy.yml"

Outputs:
  SedaiIntegrationServiceRoleName:
    Description: Sedai Role Name
    Value:
      Ref: SedaiIntegrationServiceRole
    Export:
      Name: SedaiIntegrationServiceRoleName
  SedaiIntegrationServiceRoleArn:
    Description: Sedai Role Arn
    Value:
      Fn::GetAtt: [SedaiIntegrationServiceRole, Arn]
    Export:
      Name: SedaiIntegrationServiceRoleArn
