apiVersion: batch/v1
kind: Job
metadata:
  name: sedai-kube-topo-reader
spec:
  template:
    spec:
      containers:
        - name: kube-topo-reader
          image: sedaiinc/sedaikubetoporeader:5_25_22_9_15PM
          args:
            - "my-cluster"
            - "/home/sedai/"
            - "true" 
          env:
            - name: LOG_FOLDER
              value: /home/sedai/
      restartPolicy: Never
  backoffLimit: 4
