

○ API Groups - Core, Apps 
○ Actions - Get/Watch/List
○ Resources - All (Nodes, Pods, Deployments, ReplicaSets, Replication Controllers, StatefulSets, Jobs, CronJobs, Services, EndPoints)


---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  name: datadog
  labels: {}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  - apiGroups: # Kubelet connectivity
      - ""
    resources:
      - nodes/metrics
      - nodes/spec
      - nodes/proxy
      - nodes/stats
    verbs:
      - get
  - apiGroups: # leader election check
      - ""
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - datadog
  - apiGroups:
      - "security.openshift.io"
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - datadog
      - hostaccess
      - privileged
  - apiGroups: # leader election check
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRoleBinding
metadata:
  name: datadog
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog
subjects:
  - kind: ServiceAccount
    name: datadog
    namespace: default
