AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role and policies for Sedai Integration - Billing Account - LEGACY
Resources:
  CURS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName:
        Fn::Sub: "sedai-cur-de-bucket-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Object&Version Expiration
            Status: Enabled
            NoncurrentVersionExpirationInDays: 32 # 1 month 

  CURS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Bucket:
        Ref: CURS3Bucket
      PolicyDocument:
        Id: CURS3BucketPolicy
        Version: "2012-10-17"
        Statement:
          - Sid: AllowBilling
            Effect: Allow
            Principal:
              Service: 
              - "billingreports.amazonaws.com"
              - "bcm-data-exports.amazonaws.com"
                
            Action:
                - "s3:PutObject"
                - "s3:GetBucketPolicy"
            Resource:
              - Fn::Sub: 'arn:${AWS::Partition}:s3:::${CURS3Bucket}'
              - Fn::Sub: 'arn:${AWS::Partition}:s3:::${CURS3Bucket}/*'
            Condition:
              StringLike:
                aws:SourceAccount:  !Sub "${AWS::AccountId}"
                aws:SourceArn:
                  - Fn::Sub: "arn:aws:cur:us-east-1:${AWS::AccountId}:definition/*"
                  - Fn::Sub: "arn:aws:bcm-data-exports:us-east-1:${AWS::AccountId}:export/*"

            
  CostAndUsageReport:
    Type: AWS::CUR::ReportDefinition
    DependsOn: CURS3BucketPolicy
    Properties:
      ReportName: "sedai-cur-reports"
      S3Bucket: !Ref CURS3Bucket
      S3Prefix: !Sub "cur/${AWS::AccountId}"
      S3Region: !Ref AWS::Region
      Format: "textORcsv"
      Compression: "GZIP"
      TimeUnit: "HOURLY"
      ReportVersioning: "OVERWRITE_REPORT"
      RefreshClosedReports: true
      AdditionalSchemaElements:
        - "RESOURCES"
