AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role and policies for Sedai Integration - Billing Account
Parameters:
  CURS3Bucket:
    Type: String
    Description: Name of the S3 bucket for Cost and Usage Reports

Resources:
  SedaiIntegrationBillingAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sedai-integration-billing-account-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 504216784688
            Action:
              - sts:AssumeRole
      Path: "/"

  SedaiIntegrationBillingAccountPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: sedai-integration-billing-account-role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - Fn::Sub: "arn:${AWS::Partition}:s3:::${CURS3Bucket}"
              - Fn::Sub: "arn:${AWS::Partition}:s3:::${CURS3Bucket}/*"
          - Effect: Allow
            Action:
              - savingsplans:DescribeSavingsPlans
              - ce:GetReservationCoverage
              - ce:GetReservationPurchaseRecommendation
              - ce:GetReservationUtilization
              - ce:GetSavingsPlanPurchaseRecommendationDetails
              - ce:GetSavingsPlansCoverage
              - ce:GetSavingsPlansPurchaseRecommendation
              - ce:GetSavingsPlansUtilization
              - ce:GetSavingsPlansUtilizationDetails
            Resource: "*"
      Roles:
        - Ref: "SedaiIntegrationBillingAccountRole"
