apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sedai-autonomous-mode-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - services
  - pods
  verbs:
  - get 
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get 
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  - autoscaling.k8s.io 
  resources:
  - horizontalpodautoscalers
  - VerticalPodAutoscaler
  verbs:
  - get 
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get 
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get 
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingressclasses
  - networkpolicies
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sedai-autonomous-mode-clusterrole-binding
subjects:
- kind: Group
  name: service-account-sedai-integration@PROJECT_ID.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sedai-autonomous-mode-clusterrole
  apiGroup: rbac.authorization.k8s.io
