AWSTemplateFormatVersion: 2010-09-09
Description: IAM User and policies for Sedai Integration - Autonomous
Resources:
  SedaiIntegrationServiceUser:
    Type: AWS::IAM::User
    Properties:
      UserName: sedai-integration-service-user
  SedaiIntegrationAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref SedaiIntegrationServiceUser
  SedaiIntegrationSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: sedai-integration-service-user-accesskey
      Description: Access key for Sedai user
      SecretString: !Sub '{"AccessKeyId":"${SedaiIntegrationAccessKey}","SecretAccessKey":"${SedaiIntegrationAccessKey.SecretAccessKey}"}'
  SedaiIntegrationServicePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: sedai-integration-service-role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:Describe*
              - tag:GetResources
            Resource: '*'
          - Effect: Allow
            Action:
              - autoscaling:Describe*
              - autoscaling:CreateAutoScalingGroup
              - autoscaling:CreateLaunchConfiguration
              - autoscaling:UpdateAutoScalingGroup
            Resource: '*'
          - Effect: Allow
            Action:
              - application-autoscaling:Describe*
              - application-autoscaling:DeleteScalingPolicy
              - application-autoscaling:DeregisterScalableTarget
              - application-autoscaling:PutScalingPolicy
              - application-autoscaling:RegisterScalableTarget              
            Resource: '*'
          - Effect: Allow
            Action:
              - appmesh:List*
              - appmesh:Describe*
            Resource: '*'
          - Effect: Allow
            Action:
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*            
            Resource: '*'
          - Effect: Allow
            Action:
              - dynamodb:List*
              - dynamodb:Describe*
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: '*'
          - Effect: Allow
            Action:
              - tag:GetResources
            Resource: '*' 
          - Effect: Allow
            Action:
              - ec2:Describe*
            Resource: '*'                                    
          - Effect: Allow
            Action:
              - ecs:Describe*
              - ecs:List*
              - ecs:CreateCapacityProvider
              - ecs:CreateService
              - ecs:CreateTaskSet
              - ecs:DeleteCapacityProvider
              - ecs:Deregister*
              - ecs:DiscoverPollEndpoint
              - ecs:ExecuteCommand
              - ecs:Poll
              - ecs:Put*
              - ecs:Register*
              - ecs:RunTask
              - ecs:Start*
              - ecs:StopTask
              - ecs:Submit*
              - ecs:TagResource
              - ecs:UntagResource
              - ecs:Update*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - eks:List*
              - eks:Describe*
            Resource: '*'        
          - Effect: Allow
            Action:
              - elasticloadbalancing:Describe*
              - elasticloadbalancing:CreateRule
              - elasticloadbalancing:CreateTargetGroup
              - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
              - elasticloadbalancing:RegisterInstancesWithLoadBalancer
              - elasticloadbalancing:DeregisterTargets
              - elasticloadbalancing:RegisterTargets
              - elasticloadbalancing:AddTags
            Resource: '*'
          - Action: iam:PassRole
            Effect: Allow
            Resource: '*'
            Condition:
              StringLike:
                iam:PassedToService: 
                  - ecs-tasks.amazonaws.com
                  - ec2.amazonaws.com
                  - application-autoscaling.amazonaws.com
                  - elasticloadbalancing.amazonaws.com
          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: '*'
            Condition:
              StringLike:
                iam:AWSServiceName:
                  - autoscaling.amazonaws.com
                  - ecs.amazonaws.com
                  - ecs.application-autoscaling.amazonaws.com
                  - spot.amazonaws.com
                  - spotfleet.amazonaws.com  
          - Effect: Allow
            Action:
              - lambda:Get*
              - lambda:List*
              - lambda:DeleteProvisionedConcurrencyConfig
              - lambda:PublishVersion
              - lambda:PutFunctionConcurrency
              - lambda:PutProvisionedConcurrencyConfig
              - lambda:UpdateAlias
              - lambda:UpdateFunctionConfiguration  
            Resource: '*'  
          - Effect: Allow
            Action:
              - servicediscovery:Get*
              - servicediscovery:List*            
              - servicediscovery:CreatePrivateDnsNamespace
              - servicediscovery:CreateService
              - servicediscovery:UpdateService
            Resource: '*'
          - Effect: Allow
            Action:
              - states:List*
              - states:Get*
              - states:Describe*
            Resource: '*'            
          - Effect: Allow
            Action:
              - xray:Get*
              - xray:List*              
              - xray:BatchGetTraces
            Resource: '*'
          - Action:
              - logs:Get*
              - logs:List*
              - logs:Describe*  
              - logs:TestMetricFilter
              - logs:FilterLogEvents
              - logs:GetLogEvents          
              - logs:StartQuery
              - logs:StopQuery
            Effect: Allow
            Resource: '*'
          - Effect: Allow
            Action:
              - kinesis:DescribeStream
              - kinesis:ListStreams
            Resource: '*'
      Users:
        - Ref: "SedaiIntegrationServiceUser"
Outputs:
  SedaiIntegrationAccessKey:
    Description: Sedai User Access Key
    Value:
      Ref: SedaiIntegrationAccessKey
  SedaiIntegrationSecrets:
    Description: Sedai Secret Arn where the AccessKey:SecretKey pair ( iam credentials ) of Sedai User is stored
    Value:
      Ref: SedaiIntegrationSecrets
