AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template to provide permission for Sedai
Metadata:
  AWS::Cloudformation::Interfaces:
    ParameterGroups:
      - Label:
          default: "Sedai app configuration section"
        Parameters:
          - UniqueExternalId
      - Label:
          default: "Permission section"
        Parameters:
          - IsReadOnly
          - ServerlessRequired
          - ECSRequired
          - KubernetesRequired
    ParameterLabels:
      UniqueExternalId:
        default: "Enter the unique external ID"
      IsReadOnly:
        default: "Do you want Sedai to only have read-only access to your account?"
      ServerlessRequired:
        default: "Would you like to give Sedai the permissions to optimise your Serverless workloads?"
      ECSRequired:
        default: "Would you like to give Sedai the permissions to optimise your ECS workloads?"
      KubernetesRequired:
        default: "Would you like to give Sedai the permissions to optimise your EKS workloads?"

Parameters:
  UniqueExternalId:
    Type: String
    Description: "Keep this empty (recommended) to generate a unique external ID in the ext-{AWSAccountID} format."
  IsReadOnly:
    Description: "Select yes to give read-only access. Select no if you want to give Sedai the permission to start optimizing the workloads"
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  ServerlessRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  ECSRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  KubernetesRequired:
    Description: "Select Yes or No. Please note that Sedai will not have permission to optimize the workload if read-only access is set as 'Yes'"
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  

Mappings:

Conditions:
  UniqueExternalIdPresent: !Not
    - !Equals
      - !Ref UniqueExternalId
      - ""

Resources:
  SedaiIntegrationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sedai-integration-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 504216784688
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals: !If
                - UniqueExternalIdPresent
                - sts:ExternalId: !Ref UniqueExternalId
                - sts:ExternalId: !Sub ext-${AWS::AccountId}
      Path: "/"
  SedaiIntegrationReadOnlyPolicy:
    Type: AWS

  

Outputs:
  SedaiIntegrationServiceRoleName:
    Description: Sedai Role Name
    Value:
      Ref: SedaiIntegrationServiceRole
  SedaiIntegrationServiceRoleArn:
    Description: Sedai Role Arn
    Value:
      Fn::GetAtt: [SedaiIntegrationServiceRole, Arn]