AWSTemplateFormatVersion: 2010-09-09
Description: IAM User and policies for Sedai Integration - Autonomous
Resources:
  SedaiIntegrationServiceUser:
    Type: AWS::IAM::User
    Properties:
      UserName: sedai-integration-service-user
  SedaiIntegrationAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref SedaiIntegrationServiceUser
  SedaiIntegrationSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: sedai-integration-service-user-accesskey
      Description: Access key for Sedai user
      SecretString: !Sub '{"AccessKeyId":"${SedaiIntegrationAccessKey}","SecretAccessKey":"${SedaiIntegrationAccessKey.SecretAccessKey}"}'
  SedaiIntegrationServicePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: sedai-integration-service-role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "ec2:Describe*"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeVpcs"
              - "tag:GetResources"
            Resource: "*"
          - Effect: Allow
            Action: "elasticloadbalancing:Describe*"
            Resource: "*"
          - Effect: Allow
            Action: "autoscaling:Describe*"
            Resource: "*"
          - Effect: Allow
            Action: "application-autoscaling:Describe*"
            Resource: "*"  
          - Effect: Allow
            Action:
              - "ecs:DescribeClusters"
              - "ecs:DescribeContainerInstances"
              - "ecs:DescribeServices"
              - "ecs:DescribeTaskDefinition"
              - "ecs:DescribeTasks"
              - "ecs:DiscoverPollEndpoint"                
              - "ecs:DescribeTaskSets"
              - "ecs:DescribeCapacityProviders"
              - "ecs:ListAccountSettings"
              - "ecs:ListAttributes"
              - "ecs:ListClusters"
              - "ecs:ListContainerInstances"
              - "ecs:ListServices"
              - "ecs:ListTagsForResource"
              - "ecs:ListTaskDefinitionFamilies"
              - "ecs:ListTaskDefinitions"
              - "ecs:ListTasks"
              - "ecs:CreateCapacityProvider"
              - "ecs:DeleteCapacityProvider"
              - "ecs:DeregisterContainerInstance"
              - "ecs:DeregisterTaskDefinition"
              - "ecs:Poll"
              - "ecs:PutAttributes"
              - "ecs:PutClusterCapacityProviders"
              - "ecs:RegisterContainerInstance"
              - "ecs:RegisterTaskDefinition"
              - "ecs:TagResource"
              - "ecs:UntagResource"
              - "ecs:UpdateCapacityProvider"
              - "ecs:UpdateCluster"
              - "ecs:UpdateClusterSettings"
              - "ecs:UpdateContainerAgent"
              - "ecs:UpdateContainerInstancesState"
              - "ecs:UpdateService"
              - "ecs:UpdateServicePrimaryTaskSet"
              - "ecs:UpdateTaskSet"    
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "dynamodb:BatchGetItem"
              - "dynamodb:DescribeStream"
              - "dynamodb:DescribeTable"
              - "dynamodb:GetItem"
              - "dynamodb:ListStreams"
              - "dynamodb:ListTables"
              - "dynamodb:Query"
              - "dynamodb:Scan"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "lambda:Get*"
              - "lambda:List*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "kinesis:DescribeStream"
              - "kinesis:ListStreams"
            Resource: "*"
          - Action:
              - "cloudwatch:ListMetrics"
              - "cloudwatch:GetMetricStatistics"
              - "cloudwatch:Describe*"
              - "cloudwatch:Get*"
              - "cloudwatch:List*"
              - "cloudwatch:Describe*"
              - "cloudwatch:Get*"
              - "cloudwatch:List*"
              - "logs:Get*"
              - "logs:List*"
              - "logs:StartQuery"
              - "logs:StopQuery"
              - "logs:Describe*"
              - "logs:TestMetricFilter"
              - "logs:FilterLogEvents"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
              - "logs:DescribeMetricFilters"
              - "logs:GetLogEvents"
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action:
              - "xray:GetSamplingRules"
              - "xray:GetSamplingTargets"
              - "xray:GetSamplingStatisticSummaries"
              - "xray:BatchGetTraces"
              - "xray:GetServiceGraph"
              - "xray:GetTraceGraph"
              - "xray:GetTraceSummaries"
              - "xray:GetGroups"
              - "xray:GetGroup"
              - "xray:ListTagsForResource"
              - "xray:GetTimeSeriesServiceStatistics"
              - "xray:GetInsightSummaries"
              - "xray:GetInsight"
              - "xray:GetInsightEvents"
              - "xray:GetInsightImpactGraph"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "states:ListStateMachines"
              - "states:ListActivities"
              - "states:DescribeStateMachine"
              - "states:DescribeStateMachineForExecution"
              - "states:ListExecutions"
              - "states:DescribeExecution"
              - "states:GetExecutionHistory"
              - "states:DescribeActivity"
            Resource: "*"
          - Effect: Allow
            Action:
              - "ec2:DescribeInstances"
              - "ec2:DescribeInstanceStatus"
              - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
              - "elasticloadbalancing:DescribeInstanceHealth"
              - "elasticloadbalancing:DescribeLoadBalancers"
              - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
              - "elasticloadbalancing:DeregisterTargets"
              - "elasticloadbalancing:DescribeTargetHealth"
              - "elasticloadbalancing:DescribeTargetHealth"
              - "elasticloadbalancing:RegisterTargets"
              - "elasticloadbalancing:DescribeTargetHealth"
            Resource: "*"
          - Effect: Allow
            Action:
              - "lambda:Get*"
              - "lambda:List*"
              - "lambda:UpdateFunctionConfiguration"
              - "lambda:UpdateAlias"
              - "lambda:PutFunctionConcurrency"
              - "lambda:PutProvisionedConcurrencyConfig"
              - "lambda:PublishVersion"
              - "lambda:DeleteProvisionedConcurrencyConfig"
            Resource: "*"
      Users:
        - Ref: "SedaiIntegrationServiceUser"
Outputs:
  SedaiIntegrationAccessKey:
    Description: Sedai User Access Key
    Value:
      Ref: SedaiIntegrationAccessKey
  SedaiIntegrationSecrets:
    Description: Sedai Secret Arn where the AccessKey:SecretKey pair ( iam credentials ) of Sedai User is stored
    Value:
      Ref: SedaiIntegrationSecrets
