AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role and policies for Sedai Integration - ReadOnly
Parameters:
  UniqueExternalId:
    Type: String
    Description: External ID for Trusted entities. Leave this empty to use an external ID generated based on the AWS Account ID
Conditions:
  UniqueExternalIdPresent: !Not
    - !Equals
      - !Ref UniqueExternalId
      - ""
Resources:
  SedaiIntegrationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sedai-integration-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 504216784688
            Action:
              - sts:AssumeRole
            Condition: 
              StringEquals: !If 
                - UniqueExternalIdPresent
                - sts:ExternalId: !Ref UniqueExternalId
                - sts:ExternalId: !Sub ext-${AWS::AccountId}
      Path: "/"
  SedaiIntegrationServicePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: sedai-integration-service-role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "autoscaling:Describe*"
            Resource: "*"
          - Effect: Allow
            Action: "application-autoscaling:Describe*"
            Resource: "*"  
          - Effect: Allow
            Action: 
              - appmesh:Describe*
              - appmesh:List*
            Resource: "*"
          - Effect: Allow
            Action: 
              - "cloudwatch:Describe*"
              - "cloudwatch:Get*"
              - "cloudwatch:List*" 
            Resource: "*"
          - Effect: Allow
            Action: 
              - "dynamodb:List*"
              - "dynamodb:Describe*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "ec2:Describe*"
              - "tag:GetResources"
            Resource: "*"
          - Effect: Allow
            Action:
              - "ecs:Describe*"
              - "ecs:List*"
            Resource: "*"
          - Effect: Allow
            Action: 
              - "eks:Describe*"
              - "eks:List*"
            Resource: "*"
          - Effect: Allow
            Action: "elasticloadbalancing:Describe*"
            Resource: "*"    
          - Effect: Allow
            Action:
              - "lambda:Get*"
              - "lambda:List*"
            Resource: "*"    
          - Effect: Allow
            Action:
              - "servicediscovery:Get*"
              - "servicediscovery:List*"
            Resource: "*"        
          - Effect: Allow
            Action:
              - "states:List*"
              - "states:Get*"
              - "states:Describe*"
            Resource: "*"     
          - Effect: Allow
            Action:
              - "xray:Get*"
              - "xray:List*"
              - "xray:BatchGetTraces"
            Resource: "*"                               
          - Effect: Allow
            Action:
              - "logs:List*"
              - "logs:Describe*"
              - "logs:StartQuery"
              - "logs:StopQuery"
              - "logs:TestMetricFilter"
              - "logs:GetQueryResults"
            Resource: "*"
          - Effect: Allow
            Action:
              - apigateway:GET
            Resource: '*'
      Roles:
        - Ref: "SedaiIntegrationServiceRole"
Outputs:
  SedaiIntegrationServiceRoleName:
    Description: Sedai Role Name
    Value:
      Ref: SedaiIntegrationServiceRole
  SedaiIntegrationServiceRoleArn:
    Description: Sedai Role Arn
    Value:
      Fn::GetAtt: [SedaiIntegrationServiceRole, Arn]
