AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role and policies for Sedai Integration - Autonomous
Parameters:
  UniqueExternalId:
    Type: String
    Description: External ID for Trusted entities. Leave this empty to use an external ID generated based on the AWS Account ID
Conditions:
  UniqueExternalIdPresent: !Not
    - !Equals
      - !Ref UniqueExternalId
      - ""
Resources:
  SedaiIntegrationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sedai-integration-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 504216784688
            Action:
              - sts:AssumeRole
            Condition: 
              StringEquals: !If 
                - UniqueExternalIdPresent
                - sts:ExternalId: !Ref UniqueExternalId
                - sts:ExternalId: !Sub ext-${AWS::AccountId}
      Path: "/"
  SedaiIntegrationServicePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: sedai-integration-service-role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:Describe*
              - tag:GetResources              
            Resource: '*'
          - Effect: Allow
            Action:
              - autoscaling:Describe*
              - autoscaling:CreateAutoScalingGroup
              - autoscaling:CreateLaunchConfiguration
              - autoscaling:UpdateAutoScalingGroup
              - autoscaling:DeleteLaunchConfiguration
              - autoscaling:DeleteAutoScalingGroup
              - autoscaling:TerminateInstanceInAutoScalingGroup
              - autoscaling:PutScalingPolicy
            Resource: '*'
          - Effect: Allow
            Action:
              - application-autoscaling:Describe*
              - application-autoscaling:DeleteScalingPolicy
              - application-autoscaling:DeregisterScalableTarget
              - application-autoscaling:PutScalingPolicy
              - application-autoscaling:RegisterScalableTarget              
            Resource: '*'
          - Effect: Allow
            Action:
              - appmesh:List*
              - appmesh:Describe*
            Resource: '*'
          - Effect: Allow
            Action:
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*            
            Resource: '*'
          - Effect: Allow
            Action:
              - dynamodb:List*
              - dynamodb:Describe*
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: '*'
          - Effect: Allow
            Action:
              - tag:GetResources
            Resource: '*' 
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
              - s3:PutMetricsConfiguration
              - s3:PutIntelligentTieringConfiguration
              - s3:PutLifecycleConfiguration
            Resource: '*' 
          - Effect: Allow
            Action:
              - iam:ListInstanceProfiles
            Resource: '*' 
          - Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:Search*
              - ec2:Get*
            Resource: '*'                                    
          - Effect: Allow
            Action:
              - ecs:Describe*
              - ecs:List*
              - ecs:CreateCapacityProvider
              - ecs:CreateService
              - ecs:CreateTaskSet
              - ecs:DeleteCapacityProvider
              - ecs:Deregister*
              - ecs:DiscoverPollEndpoint
              - ecs:ExecuteCommand
              - ecs:Poll
              - ecs:Put*
              - ecs:Register*
              - ecs:RunTask
              - ecs:Start*
              - ecs:StopTask
              - ecs:Submit*
              - ecs:TagResource
              - ecs:UntagResource
              - ecs:Update*
            Resource: '*'
          - Effect: Allow
            Action:
              - eks:List*
              - eks:Describe*
            Resource: '*'        
          - Effect: Allow
            Action:
              - elasticloadbalancing:Describe*
              - elasticloadbalancing:CreateRule
              - elasticloadbalancing:CreateTargetGroup
              - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
              - elasticloadbalancing:RegisterInstancesWithLoadBalancer
              - elasticloadbalancing:DeregisterTargets
              - elasticloadbalancing:RegisterTargets
              - elasticloadbalancing:AddTags
            Resource: '*'
          - Action: iam:PassRole
            Effect: Allow
            Resource: '*'
            Condition:
              StringLike:
                iam:PassedToService: 
                  - ecs-tasks.amazonaws.com
                  - ec2.amazonaws.com
                  - application-autoscaling.amazonaws.com
                  - elasticloadbalancing.amazonaws.com
                  - autoscaling.amazonaws.com
          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: '*'
            Condition:
              StringLike:
                iam:AWSServiceName:
                  - autoscaling.amazonaws.com
                  - ecs.amazonaws.com
                  - ecs.application-autoscaling.amazonaws.com
                  - spot.amazonaws.com
                  - spotfleet.amazonaws.com  
          - Effect: Allow
            Action:
              - lambda:Get*
              - lambda:List*
              - lambda:DeleteProvisionedConcurrencyConfig
              - lambda:PublishVersion
              - lambda:PutFunctionConcurrency
              - lambda:PutProvisionedConcurrencyConfig
              - lambda:UpdateAlias
              - lambda:UpdateFunctionConfiguration  
            Resource: '*'  
          - Effect: Allow
            Action:
              - servicediscovery:Get*
              - servicediscovery:List*            
              - servicediscovery:CreatePrivateDnsNamespace
              - servicediscovery:CreateService
              - servicediscovery:UpdateService
            Resource: '*'
          - Effect: Allow
            Action:
              - states:List*
              - states:Get*
              - states:Describe*
            Resource: '*'            
          - Effect: Allow
            Action:
              - xray:Get*
              - xray:List*              
              - xray:BatchGetTraces
            Resource: '*'
          - Action:
              - logs:Get*
              - logs:List*
              - logs:Describe*  
              - logs:TestMetricFilter
              - logs:FilterLogEvents         
              - logs:StartQuery
              - logs:StopQuery
            Effect: Allow
            Resource: '*'
          - Effect: Allow
            Action:
              - kinesis:DescribeStream
              - kinesis:ListStreams
            Resource: '*'
          - Effect: Allow
            Action:
              - apigateway:GET
            Resource: '*'
          - Effect: Allow
            Action:
              - codedeploy:GetDeploymentGroup
              - codedeploy:CreateDeployment
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
            Resource: '*'
      Roles:
        - Ref: "SedaiIntegrationServiceRole"
Outputs:
  SedaiIntegrationServiceRoleName:
    Description: Sedai Role Name
    Value:
      Ref: SedaiIntegrationServiceRole
  SedaiIntegrationServiceRoleArn:
    Description: Sedai Role Arn
    Value:
      Fn::GetAtt: [SedaiIntegrationServiceRole, Arn]
