AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role and policies for Sedai Integration - Billing Account - API

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sedai app configuration section"
        Parameters:
          - UniqueExternalId

Parameters:
  UniqueExternalId:
    Type: String
    Description: "Keep this empty (recommended) to generate a unique external ID in the ext-{AWSAccountID} format."

Conditions:
  UniqueExternalIdPresent: !Not
    - !Equals
      - !Ref UniqueExternalId
      - ""

Resources:
  SedaiIntegrationBillingAccountApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sedai-integration-billing-account-api-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 504216784688
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals: !If
                - UniqueExternalIdPresent
                - sts:ExternalId: !Ref UniqueExternalId
                - sts:ExternalId: !Sub ext-${AWS::AccountId}
      Path: "/"
      
  SedaiIntegrationBillingAccountApiPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: sedai-integration-billing-account-api-role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - pricing:DescribeServices
            - pricing:GetAttributeValues
            - pricing:GetProducts
            - pricing:GetPriceListFileUrl
            - pricing:ListPriceLists
            Resource: "*"
          - Effect: Allow
            Action:
            - cur:DescribeReportDefinitions
            - cur:GetUsage*
            Resource: "*"
          - Effect: Allow
            Action:
            - ce:GetCost*
            - ce:DescribeCost*
            - ce:List*
            - ce:GetReservation*
            - ce:GetSavings*
            Resource: "*"
          - Effect: Allow
            Action:
            - purchase-orders:Get*
            - purchase-orders:List*
            Resource: "*"
      Roles:
        - Ref: "SedaiIntegrationBillingAccountApiRole"
Outputs:
  SedaiIntegrationServiceRoleName:
    Description: Sedai Role Name
    Value:
      Ref: SedaiIntegrationBillingAccountApiRole
  SedaiIntegrationServiceRoleArn:
    Description: Sedai Role Arn
    Value:
      Fn::GetAtt: [SedaiIntegrationBillingAccountApiRole, Arn]
